const translations = {
    en: {
        "deliver-to": "Deliver to",
        "location": "India",
        "signin": "Sign in",
        "account-lists": "Account & Lists",
        "returns": "Returns",
        "orders": "& Orders",
        "cart": "Cart",
        "all": "All",
        "best-sellers": "Best Sellers",
        "todays-deals": "Today's Deals",
        "mobiles": "Mobiles",
        "customer-service": "Customer Service",
        "electronics": "Electronics",
        "home-kitchen": "Home & Kitchen",
        "fashion": "Fashion",
        "books": "Books",
        "prime": "Prime",
        "shop-deals": "Shop deals in Electronics",
        "hello": "Hello,",
        "trending": "Trending",
        "best-seller": "Best Seller",
        "new-releases": "New Releases",
        "movers-shakers": "Movers and Shakers",
        "digital-content": "Digital Content And Devices",
        "echo-alexa": "Echo & Alexa",
        "fire-tv": "Fire TV",
        "kindle": "Kindle E-Reader & eBook",
        "audible": "Audible Audiobook",
        "prime-video": "Amazon Prime Video",
        "prime-music": "Amazon Prime Music",
        "shop-by-category": "Shop By Category",
        "mobiles-computers": "Mobiles, Computers",
        "mens-fashion": "Men's Fashion",
        "womens-fashion": "Women's Fashion",
        "see-all": "See All",
        "program-features": "Program & Features",
        "gift-card": "Gift card & mobile recharge",
        "flight-ticket": "Flight Ticket",
        "found-it": "#FoundIt -OnAmazon",
        "clearance-storage": "Clearance Storage",
        "help-settings": "Help & settings",
        "your-account": "Your Account",
        "customer-services": "Customer Services",
        "clothes": "Clothes",
        "see-more": "See More",
        "health-care": "Health & Personal Care",
        "furniture": "Furniture",
        "beauty-pics": "Beauty Pics",
        "pet-care": "Pet Care",
        "new-toys": "New Arrival in Toys",
        "fashion-trends": "Discover Fashion Trends",
        "back-top": "Back to Top",
        "get-know-us": "Get to Know Us",
        "careers": "Careers",
        "newsletter": "Amazon Newsletter",
        "about-amazon": "About Amazon",
        "accessibility": "Accessibility",
        "sustainability": "Sustainability",
        "press-center": "Press Center",
        "investor-relations": "Investor Relations",
        "amazon-devices": "Amazon Devices",
        "amazon-science": "Amazon Science",
        "make-money": "Make Money with Us",
        "sell-products": "Sell products on Amazon",
        "sell-business": "Sell on Amazon Business",
        "sell-apps": "Sell apps on Amazon",
        "become-affiliate": "Become an Affiliate",
        "advertise-products": "Advertise Your Products",
        "self-publish": "Self-Publish with Us",
        "host-hub": "Host an Amazon Hub",
        "see-more-money": "See More Make Money with Us",
        "payment-products": "Amazon Payment Products",
        "business-card": "Amazon Business Card",
        "shop-points": "Shop with Points",
        "reload-balance": "Reload Your Balance",
        "currency-converter": "Amazon Currency Converter",
        "help-you": "Let Us Help You",
        "covid-19": "Amazon and COVID-19",
        "shipping-rates": "Shipping Rates & Policies",
        "returns-replacements": "Return & Replacements",
        "content-devices": "Manage Your Content and Devices",
        "amazon-assistant": "Amazon Assistant",
        "help": "Help",
        "conditions": "Conditions of Use",
        "privacy-notice": "Privacy Notice",
        "ads-privacy": "Your Ads Privacy Choices"
    },
    mr: {
            "deliver-to": "वितरण करा",
            "location": "भारत",
            "signin": "साइन इन करा",
            "account-lists": "खाते आणि याद्या",
            "returns": "परतावा",
            "orders": "आणि आदेश",
            "cart": "कार्ट",
            "all": "सर्व",
            "best-sellers": "सर्वाधिक विक्री होणारे",
            "todays-deals": "आजचे सौदे",
            "mobiles": "मोबाइल",
            "customer-service": "ग्राहक सेवा",
            "electronics": "इलेक्ट्रॉनिक्स",
            "home-kitchen": "घर आणि स्वयंपाकघर",
            "fashion": "फॅशन",
            "books": "पुस्तके",
            "prime": "प्राइम",
            "shop-deals": "इलेक्ट्रॉनिक्स मध्ये सौदे खरेदी करा",
            "hello": "नमस्कार,",
            "trending": "ट्रेंडिंग",
            "best-seller": "सर्वाधिक विक्री होणारे",
            "new-releases": "नवीन प्रकाशन",
            "movers-shakers": "मूव्हर्स आणि शेकर्स",
            "digital-content": "डिजिटल सामग्री आणि उपकरणे",
            "echo-alexa": "इको आणि अलेक्सा",
            "fire-tv": "फायर टीव्ही",
            "kindle": "किंडल ई-रीडर आणि ईबुक",
            "audible": "ऑडिबल ऑडिओबुक",
            "prime-video": "अॅमेझॉन प्राइम व्हिडिओ",
            "prime-music": "अॅमेझॉन प्राइम म्युझिक",
            "shop-by-category": "वर्गवारीनुसार खरेदी करा",
            "mobiles-computers": "मोबाइल, संगणक",
            "mens-fashion": "पुरुषांची फॅशन",
            "womens-fashion": "महिलांची फॅशन",
            "see-all": "सर्व पहा",
            "program-features": "कार्यक्रम आणि वैशिष्ट्ये",
            "gift-card": "गिफ्ट कार्ड आणि मोबाइल रिचार्ज",
            "flight-ticket": "फ्लाइट तिकीट",
            "found-it": "#आम्हीआम्ही-आम्हीअॅमेझॉन",
            "clearance-storage": "स्टोरेज क्लिअरन्स",
            "help-settings": "मदत आणि सेटिंग्ज",
            "your-account": "तुमचे खाते",
            "customer-services": "ग्राहक सेवा",
            "clothes": "कपडे",
            "see-more": "अजून पहा",
            "health-care": "आरोग्य आणि वैयक्तिक काळजी",
            "furniture": "फर्निचर",
            "beauty-pics": "सौंदर्याचे फोटो",
            "pet-care": "पालकांचा काळजी",
            "new-toys": "खेळण्यांमध्ये नवीन आगमन",
            "fashion-trends": "फॅशन ट्रेंड शोधा",
            "back-top": "वर जा",
            "get-know-us": "आम्हाला जाणून घ्या",
            "careers": "करिअर्स",
            "newsletter": "अॅमेझॉन न्यूजलेटर",
            "about-amazon": "अॅमेझॉनबद्दल",
            "accessibility": "प्रवेशयोग्यता",
            "sustainability": "सततता",
            "press-center": "प्रेस सेंटर",
            "investor-relations": "गुंतवणूकदार संबंध",
            "amazon-devices": "अॅमेझॉन उपकरणे",
            "amazon-science": "अॅमेझॉन सायन्स",
            "make-money": "आमच्यासोबत पैसे कमवा",
            "sell-products": "अॅमेझॉनवर उत्पादने विक्री करा",
            "sell-business": "अॅमेझॉन बिझिनेसवर विक्री करा",
            "sell-apps": "अॅमेझॉनवर अॅप्स विक्री करा",
            "become-affiliate": "एफिलिएट बना",
            "advertise-products": "तुमची उत्पादने जाहिरात करा",
            "self-publish": "आमच्यासोबत स्व-प्रकाशन करा",
            "host-hub": "अॅमेझॉन हब होस्ट करा",
            "see-more-money": "आमच्यासोबत पैसे कमवायचे अधिक मार्ग पहा",
            "payment-products": "अॅमेझॉनच्या पेमेंट उत्पादने",
            "business-card": "अॅमेझॉन व्यवसाय कार्ड",
            "shop-points": "पोइंट्ससह खरेदी करा",
            "reload-balance": "तुमची शिल्लक रिचार्ज करा",
            "currency-converter": "अॅमेझॉन चलन परिवर्तक",
            "help-you": "तुम्हाला मदत करु द्या",
            "covid-19": "अॅमेझॉन आणि COVID-19",
            "shipping-rates": "शिपिंग दर आणि धोरणे",
            "returns-replacements": "परतावा आणि बदल",
            "content-devices": "तुमची सामग्री आणि उपकरणे व्यवस्थापित करा",
            "amazon-assistant": "अॅमेझॉन असिस्टंट",
            "help": "मदत",
            "conditions": "वापरण्याच्या अटी",
            "privacy-notice": "गोपनीयता सूचना",
            "ads-privacy": "तुमच्या जाहिरातींच्या गोपनीयता पर्याय"
        }
        
    }
    
;

function translatePage(language) {
    document.querySelectorAll('[data-translate]').forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[language] && translations[language][key]) {
            element.textContent = translations[language][key];
        }
    });
}


document.querySelector('.nav-language').addEventListener('click', () => {
    const currentLang = document.querySelector('.nav-language').getAttribute('data-lang');
    const newLang = currentLang === 'en' ? 'mr' : 'en'; 
    document.querySelector('.nav-language').setAttribute('data-lang', newLang);
    document.querySelector('.nav-language span').textContent = newLang.toUpperCase();
    translatePage(newLang);
});


translatePage('en');
